/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesSiemensWashingMachineErrorCodesRouteImport } from './routes/guides.siemens-washing-machine-error-codes'
import { Route as AreasPowaiRouteImport } from './routes/areas.powai'
import { Route as AreasMulundRouteImport } from './routes/areas.mulund'
import { Route as AreasMahimRouteImport } from './routes/areas.mahim'
import { Route as AreasDadarRouteImport } from './routes/areas.dadar'
import { Route as AreasBorivaliRouteImport } from './routes/areas.borivali'
import { Route as AreasBandraRouteImport } from './routes/areas.bandra'
import { Route as AreasAndheriRouteImport } from './routes/areas.andheri'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSiemensWashingMachineErrorCodesRoute =
  GuidesSiemensWashingMachineErrorCodesRouteImport.update({
    id: '/guides/siemens-washing-machine-error-codes',
    path: '/guides/siemens-washing-machine-error-codes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasPowaiRoute = AreasPowaiRouteImport.update({
  id: '/areas/powai',
  path: '/areas/powai',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasMulundRoute = AreasMulundRouteImport.update({
  id: '/areas/mulund',
  path: '/areas/mulund',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasMahimRoute = AreasMahimRouteImport.update({
  id: '/areas/mahim',
  path: '/areas/mahim',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDadarRoute = AreasDadarRouteImport.update({
  id: '/areas/dadar',
  path: '/areas/dadar',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBorivaliRoute = AreasBorivaliRouteImport.update({
  id: '/areas/borivali',
  path: '/areas/borivali',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBandraRoute = AreasBandraRouteImport.update({
  id: '/areas/bandra',
  path: '/areas/bandra',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAndheriRoute = AreasAndheriRouteImport.update({
  id: '/areas/andheri',
  path: '/areas/andheri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/areas/andheri': typeof AreasAndheriRoute
  '/areas/bandra': typeof AreasBandraRoute
  '/areas/borivali': typeof AreasBorivaliRoute
  '/areas/dadar': typeof AreasDadarRoute
  '/areas/mahim': typeof AreasMahimRoute
  '/areas/mulund': typeof AreasMulundRoute
  '/areas/powai': typeof AreasPowaiRoute
  '/guides/siemens-washing-machine-error-codes': typeof GuidesSiemensWashingMachineErrorCodesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/areas/andheri': typeof AreasAndheriRoute
  '/areas/bandra': typeof AreasBandraRoute
  '/areas/borivali': typeof AreasBorivaliRoute
  '/areas/dadar': typeof AreasDadarRoute
  '/areas/mahim': typeof AreasMahimRoute
  '/areas/mulund': typeof AreasMulundRoute
  '/areas/powai': typeof AreasPowaiRoute
  '/guides/siemens-washing-machine-error-codes': typeof GuidesSiemensWashingMachineErrorCodesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/areas/andheri': typeof AreasAndheriRoute
  '/areas/bandra': typeof AreasBandraRoute
  '/areas/borivali': typeof AreasBorivaliRoute
  '/areas/dadar': typeof AreasDadarRoute
  '/areas/mahim': typeof AreasMahimRoute
  '/areas/mulund': typeof AreasMulundRoute
  '/areas/powai': typeof AreasPowaiRoute
  '/guides/siemens-washing-machine-error-codes': typeof GuidesSiemensWashingMachineErrorCodesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/areas/andheri'
    | '/areas/bandra'
    | '/areas/borivali'
    | '/areas/dadar'
    | '/areas/mahim'
    | '/areas/mulund'
    | '/areas/powai'
    | '/guides/siemens-washing-machine-error-codes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/areas/andheri'
    | '/areas/bandra'
    | '/areas/borivali'
    | '/areas/dadar'
    | '/areas/mahim'
    | '/areas/mulund'
    | '/areas/powai'
    | '/guides/siemens-washing-machine-error-codes'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/areas/andheri'
    | '/areas/bandra'
    | '/areas/borivali'
    | '/areas/dadar'
    | '/areas/mahim'
    | '/areas/mulund'
    | '/areas/powai'
    | '/guides/siemens-washing-machine-error-codes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AreasAndheriRoute: typeof AreasAndheriRoute
  AreasBandraRoute: typeof AreasBandraRoute
  AreasBorivaliRoute: typeof AreasBorivaliRoute
  AreasDadarRoute: typeof AreasDadarRoute
  AreasMahimRoute: typeof AreasMahimRoute
  AreasMulundRoute: typeof AreasMulundRoute
  AreasPowaiRoute: typeof AreasPowaiRoute
  GuidesSiemensWashingMachineErrorCodesRoute: typeof GuidesSiemensWashingMachineErrorCodesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/siemens-washing-machine-error-codes': {
      id: '/guides/siemens-washing-machine-error-codes'
      path: '/guides/siemens-washing-machine-error-codes'
      fullPath: '/guides/siemens-washing-machine-error-codes'
      preLoaderRoute: typeof GuidesSiemensWashingMachineErrorCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/powai': {
      id: '/areas/powai'
      path: '/areas/powai'
      fullPath: '/areas/powai'
      preLoaderRoute: typeof AreasPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/mulund': {
      id: '/areas/mulund'
      path: '/areas/mulund'
      fullPath: '/areas/mulund'
      preLoaderRoute: typeof AreasMulundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/mahim': {
      id: '/areas/mahim'
      path: '/areas/mahim'
      fullPath: '/areas/mahim'
      preLoaderRoute: typeof AreasMahimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/dadar': {
      id: '/areas/dadar'
      path: '/areas/dadar'
      fullPath: '/areas/dadar'
      preLoaderRoute: typeof AreasDadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/borivali': {
      id: '/areas/borivali'
      path: '/areas/borivali'
      fullPath: '/areas/borivali'
      preLoaderRoute: typeof AreasBorivaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/bandra': {
      id: '/areas/bandra'
      path: '/areas/bandra'
      fullPath: '/areas/bandra'
      preLoaderRoute: typeof AreasBandraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/andheri': {
      id: '/areas/andheri'
      path: '/areas/andheri'
      fullPath: '/areas/andheri'
      preLoaderRoute: typeof AreasAndheriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AreasAndheriRoute: AreasAndheriRoute,
  AreasBandraRoute: AreasBandraRoute,
  AreasBorivaliRoute: AreasBorivaliRoute,
  AreasDadarRoute: AreasDadarRoute,
  AreasMahimRoute: AreasMahimRoute,
  AreasMulundRoute: AreasMulundRoute,
  AreasPowaiRoute: AreasPowaiRoute,
  GuidesSiemensWashingMachineErrorCodesRoute:
    GuidesSiemensWashingMachineErrorCodesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
